### ISSUE TITLE
Whoops

### ISSUE THREAD

**Issue by shafelani** [londoncyclingcampaign/lcc-dangerous-junctions#51] opened 2023-11-07 15:37 UTC
Getting error message on mobile chrome iOS.

**Comment by danielhills** [comment] 2023-11-07 15:53
Thanks for reporting - duplicate of issue reported in https://github.com/londoncyclingcampaign/lcc-dangerous-junctions/issues/50

**Closed as completed by danielhills** 2023-11-07 15:53 UTC
